Referee system feedback
PolySTAR-mtl/PolySTAR-Taproot pull request #38
Opened 2024-01-28 18:49 UTC by Heartpray3

Adding verification to the execute method of auto commands to make them wait until the game stage is in game. Creating new test commands that doesn't need referee feedback. Unmap previous mapping and mapping those new commands. & Instanciate turret Auto Aim command in ICRA.

2024-01-30 16:35 UTC, manelkdm commented on PolySTAR-Taproot-project/src/control/Icra/icra_control.cpp
> +ToggleCommandMapping toggleChassisAuto(drivers(), {&chassisAutoDrive, &turretAutoAim}, RemoteMapState(Remote::Switch::RIGHT_SWITCH, Remote::SwitchState::UP));
les noms sont pas bons, ce serait plutôt toggleAutoCommands par exemple

2024-01-30 16:36 UTC, manelkdm commented on PolySTAR-Taproot-project/src/control/Icra/icra_control.cpp
> +ToggleCommandMapping toggleChassisAuto(drivers(), {&chassisAutoDrive, &turretAutoAim}, RemoteMapState(Remote::Switch::RIGHT_SWITCH, Remote::SwitchState::UP));
les noms sont pas bons, ce serait plutôt toggleAutoCommands par exemple

2024-01-30 16:36 UTC, manelkdm commented on PolySTAR-Taproot-project/src/control/Icra/icra_control.cpp
> +ToggleCommandMapping toggleChassisTestAuto(drivers(), {&chassisTestAutoDrive, &turretTestAutoAim}, RemoteMapState(Remote::Switch::RIGHT_SWITCH, Remote::SwitchState::DOWN));
Pareil ici

2024-01-30 16:38 UTC, manelkdm commented
Il faudrait ajouter les toggle dans la fonction registerStandardIoMappings !

2024-01-30 22:43 UTC, Heartpray3 commented on PolySTAR-Taproot-project/src/control/Icra/icra_control.cpp
> +ToggleCommandMapping toggleChassisAuto(drivers(), {&chassisAutoDrive, &turretAutoAim}, RemoteMapState(Remote::Switch::RIGHT_SWITCH, Remote::SwitchState::UP));
Okay, j'avais juste réutilisé le mm nom, mais je vais changer ça

2024-02-01 00:28 UTC, manelkdm approved these changes

2024-02-01 02:32 UTC, FreshOlives requested changes

2024-02-01 02:32 UTC, FreshOlives commented on PolySTAR-Taproot-project/src/control/Icra/icra_control.cpp
> +ToggleCommandMapping toggleTestCommands(drivers(), {&chassisTestAutoDrive, &turretTestAutoAim}, RemoteMapState(Remote::Switch::RIGHT_SWITCH, Remote::SwitchState::DOWN));
Personally would rename this to `toggleAutoTestCommands`

2024-02-01 02:32 UTC, FreshOlives commented on PolySTAR-Taproot-project/src/subsystems/chassis/chassis_test_auto_drive_command.hpp
> +#ifndef CHASSIS_AUTO_DRIVE_COMMAND_HPP_
Update include guards

2024-02-01 02:32 UTC, FreshOlives commented on PolySTAR-Taproot-project/src/subsystems/chassis/chassis_test_auto_drive_command.hpp
> +#endif  // CHASSIS_AUTO_DRIVE_COMMAND_HPP_
Update command name comment

2024-02-01 02:32 UTC, FreshOlives commented on PolySTAR-Taproot-project/src/subsystems/turret/turret_test_auto_aim_command.hpp
> +#ifndef TURRET_AUTO_AIM_COMMAND_HPP_
Update include guards

2024-02-01 02:32 UTC, FreshOlives commented on PolySTAR-Taproot-project/src/subsystems/turret/turret_test_auto_aim_command.hpp
> +#endif  // TURRET_AUTO_AIM_COMMAND_HPP_
Update command name comment

2024-02-01 02:32 UTC, FreshOlives commented on PolySTAR-Taproot-project/src/control/Icra/icra_control.cpp
> +    drivers->commandMapper.addMap(&toggleTestCommands);
See above

2024-02-04 22:51 UTC, Melvice commented on PolySTAR-Taproot-project/src/subsystems/turret/turret_test_auto_aim_command.hpp
> +    /**
Review comments to adapt it for the correct file. Should be turret and not chassis

2024-02-04 22:52 UTC, Melvice commented on PolySTAR-Taproot-project/src/subsystems/turret/generic_auto_aim_command.hpp
> +     * Initializes the command with the passed in ChassisSubsystem.  Must not
review comments

2024-02-04 22:54 UTC, Melvice commented on PolySTAR-Taproot-project/src/subsystems/turret/turret_test_auto_aim_command.hpp
> +     * Initializes the command with the passed in ChassisSubsystem.  Must not
Review comments to adapt it for the correct file. Should be turret and not chassis

2024-02-04 22:55 UTC, Melvice approved these changes

2024-02-04 23:01 UTC, Melvice approved these changes

2024-02-04 23:10 UTC, merged